### ISSUE TITLE
[Screen Reader – BotKit]: "list heading" <lh> is not defined for “Platforms” and “Contributing to BotKit”.

### ISSUE THREAD

**Issue by v-gasikk** [howdyai/botkit-website#9]
**User Experience:**
Users who rely on screen readers will affect to navigate, if "list heading" <lh> is not defined for “Platforms” and “Contributing to BotKit”.

**Test Environment:**
OS: Win 10 Version 1809 (OS Build 17763.316)
URL: https://botkit.ai/
Browser: Edge
Tool Used: Developer tool bar (F 12)

**Repro Steps:**
Step 1: Open the above URL in edge browser.
Step 2: Navigate to “Docs” link and select it.
Step 3: Open developer tool bar (F 12)
Step 4: Navigate to list headings Platforms” and “Contributing to BotKit”.
Step 5: Verify whether "list heading" <lh> is not defined for “Platforms” and “Contributing to BotKit”.

**Actual Result:**
"list heading" <lh> is not defined for “Platforms” and “Contributing to BotKit”.

**Expected Result:**
"list heading" <lh> makes the most sense for “Platforms” and “Contributing to BotKit”.

**Reference Link:**
https://stackoverflow.com/questions/8935262/how-to-semantically-add-heading-to-a-list

**MAS Reference Link:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}]()
![MAS1 3 1_BotKit_list heading](https://user-images.githubusercontent.com/48272005/54434357-12381100-4754-11e9-9ae8-deec3a341baf.png)

**Comment by benbrown** [comment]
Done.

**Comment by v-gasikk** [comment]
Issue is Fixed. Hence Closing the bug.
Now "list heading" makes the most sense for “Platforms” and “Contributing to BotKit”.
